### ISSUE TITLE
PEP2.PDB

### ISSUE THREAD

**Issue by sladen** [platomav/CPUMicrocodes#11]
The listing on this driver site claims that a file called "Win95NT.zip" contains `PEP2.PDB`:
* https://www.driverguide.com/driver/detail.php?driverid=63869

…one just needs to work out how to download the actual file, rather than that the "friendly" driver updating software it tries to get people to click on.

**Comment by platomav** [comment]
I downloaded the file and the microcodes in there are also in the MCE DB. There are three corrupted ones but the DB has the proper ones included. Intel actually released that broken 1896 microcode three times. The first it had jumbled date, the second had a fixed date but bad/forgotten checksum and the third was finally proper. Since this is a continuation of #10, I'll close this and you can reply at the other.
