### ISSUE TITLE
Microcode related!

### ISSUE THREAD

**Issue by karakarga07** [platomav/CPUMicrocodes#28]
Hi,
I have investigated that, 2 microcodes are missing for Intel CPU's, those are present in Asus P3C-E and Asus P3V4X mainboard bios'es. You can extract those microcodes easily from their bios'es easily with ctmc.exe and cbrom.exe under x86 based operating system as you know. The bios files are at:

https://dlcdnets.asus.com/pub/ASUS/beta/mb/bios/1025e.zip
https://dlcdnets.asus.com/pub/ASUS/mb/slot1/pro133a/p3v4x/pv4x1064.zip

Those microcodes are not present in the databese:
- cpu00000633_plat00000001_ver00000034_date19980508.bin
- cpu00000634_plat00000001_ver00000035_date19980508.bin

The Intel database have similar ones, but flatforms are different!
cpu00633_plat00_ver00000036_1998-09-23_PRD_E92FAA0C.bin
cpu00634_plat00_ver00000037_1998-09-23_PRD_02C55597.bin

I know they are really old. :)

**Comment by platomav** [comment]
Hello,

A null Intel microcode Platform ID bitfield (00) is the same as MSB being set (01), because by definition they need to support at least one platform. Meaning:

cpu00633_plat00_ver00000034_1998-05-08_PRD_278BE7DD = cpu00633_plat01_ver00000034_1998-05-08_PRD_278BE7DC
cpu00634_plat00_ver00000035_1998-05-08_PRD_3AC2FB54 = cpu00634_plat01_ver00000035_1998-05-08_PRD_3AC2FB53

The two binary pairs are identical too, with only the Platform ID byte changing from 0x00 to 0x01 and the checksum being equivalently adjusted by 0x01.

Which means that the latest microcodes for these CPUIDs are correctly included in this repository:

cpu00633_plat00_ver00000036_1998-09-23_PRD_E92FAA0C
cpu00634_plat00_ver00000037_1998-09-23_PRD_02C55597

By the way, these old BIOS were from AWARD and you can extract them into their modules using [Award BIOS Module Extractor](https://github.com/platomav/BIOSUtilities). Afterwards, scanning the output folder with [MC Extractor](https://github.com/platomav/MCExtractor) will get you the actual microcodes and also see that they are included in the MC Extractor DB and thus considered when pushing latest Production blobs in this repository. The README explains more on that.

**Comment by karakarga07** [comment]
Very tricky, I have looked with hex editor each, very little differences. Maybe Intel changed platform name from 01 to 00 somehow? I have integrated them into bios for a walk around, the award bios utility added them both. So, unless we know for which CPU they are for, we can not exactly be sure.

Step 1 --> integrate older one for the X CPU look with hardware info the old microcode.
Step 2 --> integrate only new one for the X CPU look with hardware info the microcode if accepted.
option
Step 3 --> integrate old and new microcodes both, and look with hardware info, is the newer one chosen by this X CPU.

OK, never mind....

**Comment by platomav** [comment]
They are the same and the latest are present in this repo. I'm thus closing this issue.

**Comment by karakarga07** [comment]
Those are the many examples of same CPU ID with different platforms on the list. Your explanation is ridiculous. I have asked this issue to a good pal 2 years bigger than me about 54 years of age. He sells Oracle licenses worldwide, a French guy. He told me that, if platform is different it means different type of CPU like Celeron or Pentium for the same generation. Your explanation is definitely wrong. The site is under your administration, decision is yours..... 

cpu106C9_plat08_ver00000007_2009-02-11_PRD_62A4AD62.bin
cpu106C9_plat10_ver00000007_2009-02-13_PRD_C2DA0E36.bin

cpu106CA_plat04_ver00000107_2009-08-25_PRD_7DEB58B2.bin
cpu106CA_plat01_ver00000107_2009-08-25_PRD_F851A3D9.bin

cpu106CA_plat10_ver00000107_2009-08-25_PRD_482CAE0E.bin
cpu106CA_plat08_ver00000107_2009-08-25_PRD_BE667CA5.bin

cpu20652_plat80_ver00000006_2009-09-15_PRD_B12EF96C.bin
cpu20652_plat12_ver00000011_2018-05-08_PRD_6E121A49.bin

cpu20661_plat02_ver00000105_2011-07-18_PRD_52558795.bin
cpu20661_plat01_ver00000104_2009-10-23_PRD_38CB12B9.bin

cpu30651_plat08_ver0000010D_2013-05-20_PRD_0C8D59A0.bin
cpu30651_plat01_ver00000110_2013-10-14_PRD_854EDC90.bin

cpu30660_plat08_ver00000003_2010-11-03_PRD_0B1DEE36.bin
cpu30660_plat04_ver00000003_2010-11-03_PRD_5173ABD8.bin

cpu30661_plat02_ver0000010D_2011-12-22_PRD_D687F85A.bin
cpu30661_plat01_ver0000010D_2011-12-22_PRD_B4762578.bin
cpu30661_plat08_ver0000010F_2015-07-21_PRD_0E2514F3.bin
cpu30661_plat04_ver0000010F_2015-07-21_PRD_F422CDF9.bin

cpu30672_plat02_ver0000022E_2014-04-01_PRD_94CB9F8B.bin
cpu30672_plat01_ver0000022D_2014-01-14_PRD_72CFE73B.bin

cpu30673_plat02_ver00000329_2019-09-16_PRD_683DEB8A.bin
cpu30673_plat01_ver00000329_2019-09-16_PRD_81219E54.bin

cpu30678_plat0C_ver00000838_2019-04-22_PRD_2FCBB165.bin
cpu30678_plat02_ver00000838_2019-04-22_PRD_6BF2E4C4.bin
cpu30678_plat01_ver00000832_2015-02-09_PRD_875B494A.bin

cpu306F2_plat80_ver00000F07_2014-07-07_PRD_D88AA181.bin
cpu306F2_plat6F_ver00000049_2021-08-11_PRD_79C6E826.bin

cpu406E1_platF2_ver00000016_2014-08-06_PRD_2DFF9E39.bin
cpu406E1_plat80_ver00000020_2014-11-11_PRD_FE1CC0E2.bin

cpu406E2_platF2_ver0000000A_2014-11-05_PRD_0A13EE5F.bin
cpu406E2_platC0_ver0000002C_2015-05-21_PRD_D28F2B75.bin

cpu506D1_plat04_ver00000102_2015-06-05_PRD_04DB0C29.bin
cpu506D1_plat02_ver00000101_2014-11-20_PRD_BAB05F5F.bin

cpu806E9_platC0_ver000000F0_2021-11-12_PRD_65EB9B32.bin
cpu806E9_plat10_ver000000F0_2021-11-12_PRD_2CD41181.bin
